# render.yaml
services:
  - type: web
    name: airbnb-clone-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn airbnb_clone.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromDatabase:
          name: airbnb-clone-db
          property: connectionString
          propertyPath: password
      - key: DJANGO_ALLOWED_HOSTS
        value: "airbnb-clone.onrender.com"
      - key: DB_ENGINE
        value: "postgresql"
      - key: DB_NAME
        fromDatabase:
          name: airbnb-clone-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: airbnb-clone-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: airbnb-clone-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: airbnb-clone-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: airbnb-clone-db
          property: port
      - key: CELERY_BROKER_URL
        value: "redis://redis:6379/0"
      - key: CELERY_RESULT_BACKEND
        value: "redis://redis:6379/0"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-url.com"
      - key: FRONTEND_BASE_URL
        value: "https://your-frontend-url.com"

databases:
  - name: airbnb-clone-db
    databaseName: airbnb_clone
    user: airbnb_user
    plan: free
    deleteProtection: false